# Generated by Django 3.0.3 on 2020-03-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameID', models.CharField(max_length=120)),
                ('CompetitionID', models.CharField(max_length=120)),
                ('CompetitionName', models.CharField(max_length=120)),
                ('Date', models.CharField(max_length=120)),
                ('HomeTeamID', models.CharField(max_length=120)),
                ('HomeTeamName', models.CharField(max_length=120)),
                ('HomeTeamScore', models.IntegerField()),
                ('HomeTeamScoreHT', models.IntegerField()),
                ('AwayTeamID', models.CharField(max_length=120)),
                ('AwayTeamName', models.CharField(max_length=120)),
                ('AwayTeamScore', models.IntegerField()),
                ('AwayTeamScoreHT', models.IntegerField()),
            ],
        ),
    ]
