# Generated by Django 2.2.3 on 2020-03-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='Date',
            field=models.DateField(),
        ),
    ]
