# Generated by Django 2.2.3 on 2020-03-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200317_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='Date',
            field=models.CharField(max_length=120),
        ),
    ]
