# Generated by Django 2.2.3 on 2020-03-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200317_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='Date',
            field=models.IntegerField(),
        ),
    ]
